fusion:
  visual_feat_dim: 256  
  text_feat_dim: 256    
  hidden_dim: 512
  num_heads: 8

  output:
    pose_dim: 6
    action_dim: 5

training:
  batch_size: 64
  learning_rate: 1e-4
  temperature: 0.07
